sudo: required
dist: precise
group: edge

language: java

jdk:
- oraclejdk8
- oraclejdk9

script: ./mvnw package

cache:
  directories:
  - ~/.m2/repository
  - ~/.m2/wrapper

addons:
  apt:
    packages:
      - oracle-java9-installer