sudo: required
dist: trusty
group: edge

language: java

jdk:
- oraclejdk8
- oraclejdk11

script: ./mvnw package

after_success:
  - ./mvnw clean test jacoco:report coveralls:report

cache:
  directories:
  - ~/.m2/repository
  - ~/.m2/wrapper